//
// Module FPGA1.kuku.struct
//
// Created:
//          by - user.UNKNOWN (USER-PC)
//          at - 09:10:37 29/04/14
//
// Generated by Mentor Graphics' HDL Designer(TM) 2010.2a (Build 7)
//

`resetall
`timescale 1ns/10ps
module kuku;


// Internal Declarations


// Local declarations



// Instances 

endmodule // kuku

